language: ruby

rvm:
  - 2.4.1
  - 2.3.0
  - 2.2
  - 2.1

install:
  - "bundle install"

before_script: "bundle exec rake db:migrate"
script:        "bundle exec rake"

gemfile:
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile

matrix:
  allow_failures:
    # don't allow failures -- everything should build unless it's excluded

  exclude:
    - rvm: 2.0.0  # bug w/ ruby-2.0.0@rails-3.1 https://github.com/rails/rails/issues/9417
      gemfile: gemfiles/rails_3.1.gemfile
    - rvm: 2.1.5  # same bug as 2.0.0
      gemfile: gemfiles/rails_3.1.gemfile

addons:
    code_climate:
        repo_token: c6d8503090d42afad99391e18e71017d9592cdb4cc099db90fc4f45ef0da37c8

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
