development: &non_production_settings
  enabled: true
  delivery:
    enabled: false
    phone_number_override: "1-406-555-1212"
  twilio:
    account_sid: "account_sid"
    auth_token: "auth_token"
  ignore_paths:
    - /users/sign_out
    - /users/sign_in

test:
  enabled: true
  delivery:
    enabled: true
    phone_number_override: "1-406-555-1212"
  twilio:
    account_sid: "account_sid"
    auth_token: "auth_token"
  ignore_paths:
    - /users/sign_out
    - /users/sign_in
    
production:
  enabled: false
  delivery:
    enabled: true
  twilio:
    account_sid: "account_sid"
    auth_token: "auth_token"
  ignore_paths:
    - /users/sign_out
    - /users/sign_in