twilio_settings: &twilio_settings
  from_number: "1-###-###-####"
  account_sid: "**********************************"
  auth_token:  "********************************"
  
delivery_settings: &delivery_settings
  enabled: true
  phone_number_override: "1-###-###-####"
  
defaults: &defaults
  enabled: true
  delivery:
    <<: *delivery_settings
  twilio:
    <<: *twilio_settings
  ignore_paths:
    - /users/sign_out
    - /users/sign_in

development:
  <<: *defaults
  delivery:
    <<: *delivery_settings
    enabled: false

test:
  <<: *defaults
    
production:
  <<: *defaults
  enabled: false
